services:
  db:
    image: mariadb:11.8-ubi
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecomdb
      MYSQL_USER: ecomuser
      MYSQL_PASSWORD: ecompassword
    volumes:
      - dbdata:/var/lib/mysql
      - ./assets/db-load-script.sql:/docker-entrypoint-initdb.d/01-products.sql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "ecomuser", "-p$$MYSQL_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  website:
    depends_on:
      db:
        condition: service_healthy
    image: onetap-website:latest
    container_name: website
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_USER: ecomuser
      DB_PASSWORD: ecompassword
      DB_NAME: ecomdb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
